' *******************************************************************************************
' Copyright (c) 2023 by RobotPatient Simulators
'
' Authors: Richard Kroesen
'
' Permission is hereby granted, free of charge, to any person obtaining a copy
' of this software and associated documentation files (the "Software"),
' to deal in the Software without restriction,
'
' including without limitation the rights to use, copy, modify, merge, publish, distribute,
' sublicense, and/or sell copies of the Software, and to permit persons to whom the Software
' is furnished to do so,
'
' subject to the following conditions:
'
' The above copyright notice and this permission notice shall be included in
' all copies or substantial portions of the Software.
'
' THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
' IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
' FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
'
' IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
' DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
' ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
' OTHER DEALINGS IN THE SOFTWARE.
' *********************************************************************************************/

@startuml INP_class_diagram_puml

set separator ::

package Manikin_Software_Libraries <<Node>> {
    package com_intranet <<frame>> {
        ' Package indicates the working directory.
        namespace com::intranet {
            class I2C_driver {
                All TwoWire functions are wrapped here.
            }

            class hub_registers {

            }

            class inp_register {

            }

            class master_inp {
                acts as i2c master.
            }

            class hub_inp {
                Acts as i2c slave.
            }

            I2C_driver -- master_inp
            I2C_driver -- hub_inp
            hub_inp -- hub_registers
            hub_registers -- inp_register
        }
    }
}

' Classes Relationships.

@enduml